### ISSUE TITLE
ZIF_APACK_MANIFEST  shouldn't be part of this repo

### ISSUE THREAD

**Issue by christianguenter2** [hardyp/ABAPToTheFuture04#12]
As ZIF_APACK_MANIFEST is automatically created by abapGit, I think it should be part of this repo.
![grafik](https://user-images.githubusercontent.com/17437789/144979204-7f361dd5-490a-425e-8408-be7e81d5cf18.png)

**Comment by hardyp** [comment]
OK .... it is gone!
