### ISSUE TITLE
ZIF_CREATED_VIA_OCP_FACTORY can not found

### ISSUE THREAD

**Issue by ttkk1024** [hardyp/ABAPToTheFuture04#14]
https://github.com/hardyp/ABAPToTheFuture04/blob/6f08a10fd8e82ad7602c79fcd92a831537b13e99/src/z4_00_core_objects/z4_002_abap/z4_002_alv_framework/zcl_bc_view_salv_table.clas.abap#L10

![微信截图_20220831153130](https://user-images.githubusercontent.com/145719/187619639-f145829d-6070-411c-b470-d16b082054d6.png)
this is my error . How can find the ZIF_CREATED_VIA_OCP_FACTORY? Thank you very much.

**Comment by larshp** [comment]
guess its from https://github.com/hardyp/OCPFactory/tree/main/src
