### ISSUE TITLE
repo size

### ISSUE THREAD

**Issue by larshp** [hardyp/ABAPToTheFuture04#6]
the `z4_012_monster` folder is around 350mb you might want to reduce the size?

![image](https://user-images.githubusercontent.com/5888506/142147471-e9d1d975-3a4d-41f6-93f0-af558ee13f13.png)

**Comment by hardyp** [comment]
This is because of all the funny JavaScript things which got added when I imported a UI5 app into SAP. There are thousands of the things. Is there a way to exclude anything with ZMONSTERSVSFS in the name?

**Comment by hardyp** [comment]
Maybe if I take the root BSP application package out of the class. I will try that.

**Comment by hardyp** [comment]
There we go. Thousands of un-needed files removed.

**Comment by larshp** [comment]
"7,660 changed files with 0 additions and 1,484,526 deletions"

👍 

closing
