### ISSUE TITLE
interface ZIF_BC_ALV_REPORT_VIEW

### ISSUE THREAD

**Issue by larshp** [hardyp/ABAPToTheFuture04#8]
I cannot find ZIF_BC_ALV_REPORT_VIEW is it in a dependency somewhere?

**Comment by hardyp** [comment]
It was in the wrong package. The good thing is this exposed an error in my "dependency analyser" program, which I have now fixed, so I may well find more such missing interfaces. Anyway, the above interface is uploaded to the repository now.

**Comment by larshp** [comment]
no need to invent something, just run the linter :)
