### ISSUE TITLE
mockup loader?

### ISSUE THREAD

**Issue by larshp** [hardyp/ABAPToTheFuture04#9]
in https://github.com/sbcgua/mockup_loader/blob/master/src/zcl_mockup_loader.clas.abap

I cannot find methods `class_set_source` and `get_instance`? are you using a different loader?

```abap
    zcl_mockup_loader=>class_set_source(
      i_type = 'MIME'
      i_path = 'ZMONSTER_TEST_DATA' ).

    TRY.
        DATA(mockup_loader) = zcl_mockup_loader=>get_instance( ).
```

![image](https://user-images.githubusercontent.com/5888506/142422824-62c96a7d-c09a-48a1-860a-f3a635ab0c15.png)

**Comment by hardyp** [comment]
I downloaded the latest version of the project and the way you create an instance has been simplified - two methods calls have been reduced down to one, which is much better. I have updated my code to match,

**Comment by larshp** [comment]
cool, 👍 

https://github.com/hardyp/ABAPToTheFuture04/commit/c79815cb54c42b38922285e766d599651ce1a94c
